#!/usr/bin/env bash


#
#-----------------------------------------------------------------------
#
# This J-Job script runs a set of tests at the end of WE2E tests.
#
# Run-time environment variables:
#
#    GLOBAL_VAR_DEFNS_FP
#    CDATE
#    FCST_DIR
#    SLASH_ENSMEM_SUBDIR
#
# Experiment variables
#
#  user:
#    RUN_ENV
#    SCRIPTSdir
#    USHdir
#
#  workflow:
#    FCST_LEN_HRS
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. $USHdir/source_util_funcs.sh
sections=(
  user
  nco
  workflow
  task_aqm_use_case_data_download.envars
)
for sect in ${sections[*]} ; do
  source_yaml ${GLOBAL_VAR_DEFNS_FP} ${sect}
done
. $USHdir/job_preamble.sh

#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; . $USHdir/preamble.sh; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the regional integration test task
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set grid name and COMOUT locations.
#
#-----------------------------------------------------------------------
#
#if [ "${RUN_ENVIR}" != "nco" ]; then
#  export fcst_dir="${FCST_DIR}${SLASH_ENSMEM_SUBDIR}"
#else
#  export fcst_dir="${FCST_DIR}"
#fi
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary variables.
#
#-----------------------------------------------------------------------
#

if [ -d "${AQM_STAGE_DST_DIR}/FV3GFS" ]; then
  print_info_msg "AQM data stage directory already exists - assuming data is staged correctly. Remove this directory to re-stage."
else
  print_info_msg "Staging AQM use case data"

  mkdir -p "${AQM_STAGE_DST_DIR}"

  EXTRN_MDL_CDATE="2023-06-01 12:00:00"
  data_stores="aws"
  EXTRN_MDL_NAME="UFS-AQM-S3"
  fcst_hrs=( "0" )
  file_set="obs"
  additional_flags=""
  EXTRN_DEFNS="${EXTRN_MDL_VAR_DEFNS_FN}.sh"

  #tdk:aqm-data
  cmd="
  python3 -u ${USHdir}/retrieve_data.py \
    --debug \
    --file_set ${file_set} \
    --config ${PARMdir}/data_locations.yml \
    --cycle_date ${EXTRN_MDL_CDATE} \
    --data_stores ${data_stores} \
    --data_type ${EXTRN_MDL_NAME} \
    --fcst_hrs ${fcst_hrs[@]} \
    --output_path ${AQM_STAGE_DST_DIR} \
    --summary_file ${EXTRN_DEFNS} \
    $additional_flags"

  $cmd
  export err=$?
  if [ $err -ne 0 ]; then
    message_txt="Call to retrieve_data.py failed with a non-zero exit status.
  The command was:
  ${cmd}
  "
    if [ "${RUN_ENVIR}" = "nco" ] && [ "${MACHINE}" = "WCOSS2" ]; then
      err_exit "${message_txt}"
    else
      print_err_msg_exit "${message_txt}"
    fi
  fi

#  cp -rvs /gpfs/f6/bil-fire8/proj-shared/Benjamin.Koziol/for-aqm-use-case-proto/UFS-AQM/* "${AQM_STAGE_DST_DIR}"
  cd "${AQM_STAGE_DST_DIR}"

  tar -xvf RESTART/RESTART-20230531.tar
  rm RESTART/RESTART-20230531.tar

  find RAVE_fire -iname "*.tar" -exec tar -xvf {} \;
  rm RAVE_fire/*.tar
fi

#cp -rv /gpfs/f6/bil-fire8/proj-shared/Benjamin.Koziol/for-aqm-use-case-proto/UFS-AQM/* "${AQM_STAGE_DST_DIR}"


#if [ "${TEST_UFS_FIRE}" = "True" ]; then
#  TEST_UFS_FIRE_FLAG="--test_ufs_fire"
#else
#  TEST_UFS_FIRE_FLAG=""
#fi
#$SCRIPTSdir/exregional_integration_test.py \
#           --fcst_dir=$fcst_dir \
#           --fcst_len=${FCST_LEN_HRS} \
#           "${TEST_UFS_FIRE_FLAG}" || \
#print_err_msg_exit "\
#Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Run job postamble.
#
#-----------------------------------------------------------------------
#
job_postamble
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

